service: EC2RecoveryCheck

frameworkVersion: '2'

package:
  individually: true
  exclude:
    - ./**

provider:
  name: aws
  runtime: python2.7
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-southeast-2
  iam:
    role:
      managedPolicies:
        - 'arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess'

functions:
  ec2recovery:
    description: Check for EC2 fault tolerance coverage in an AWS account
    handler: handler.handler_name
    package:
      include:
        - handler.py
    timeout: 10
    environment:
      CHECK_REFRESH_SECONDS: 300
    events:
      - httpApi:
          path: /ec2recovery
          method: get